### ISSUE TITLE
dumpsys

### ISSUE THREAD

**Issue by arm64-v9a** [entr0pia/trichromelibrary-squoosh#1]
`dumpsys package|grep name:c`

shell权限就可以获取trichrome的version

**Comment by entr0pia** [comment]
感谢提供的方法

**Comment by ValeZAA** [comment]
https://android.stackexchange.com/q/242721/316592

>###UPDATE AUGUST 2022###

>Latest Trichrome updates (I'm now on 511.209.733) seem to take care of old versions disinstalling them and leaving only the latest, no more need to manually delete in /data/app and /data/data


But your script still removed some for Canary. Thanks.
