### ISSUE TITLE
When squooshing is performed?

### ISSUE THREAD

**Issue by giving-sesame** [entr0pia/trichromelibrary-squoosh#2]
I'm sorry, maybe I was not attentive enough, but I did not find the description at what moment your script does this decimation of redundant trichromelibraries: after reboot or periodically or whatever? Could you please explain?

**Comment by entr0pia** [comment]
If you install it as a Magisk module, the script will check for excess Trichromelibrary and remove it after each system reboot.

**Comment by giving-sesame** [comment]
I see, thank you. Is it possible to run your script any time via terminal?

**Comment by entr0pia** [comment]
Of course you can. Run the following command in a terminal with **root** privileges: `sh /data/adb/modules/trichromelibrary-squoosh/service.sh`.

**Comment by giving-sesame** [comment]
Thank you!
