### ISSUE TITLE
Can't remove

### ISSUE THREAD

**Issue by HuaJiOS** [entr0pia/trichromelibrary-squoosh#3]
I have tried the newest module on android 10 and 12. It can remove newer library, but can't remove older library.

**Comment by njtony11** [comment]
A12用1.3.1没有效果，清除不了，用最原始的1.2可以

**Comment by entr0pia** [comment]
漏了一个双引号, 现在应该正常了

**Comment by HuaJiOS** [comment]
早知道是中国人的话，我就不强行英语了
