### ISSUE TITLE
Add support for "com.google.android.trichromelibrary.beta"?

### ISSUE THREAD

**Issue by HarriBuh** [entr0pia/trichromelibrary-squoosh#6]
I recently noticed a new trichrome library in "data/user/0/com.google.android.trichromelibrary.beta_642202633" and its base.apk is 191 MB.

I'm on a Google Pixel 7 with Android 14.

1. Is the beta safe to delete/ uninstall/ "squoosh"?

2. If so, can you please update your app to support it?

**Comment by entr0pia** [comment]
It safely removes beta versions of libraries, which cannot be performed if the library is in use.
