### ISSUE TITLE
Module will not install on latest Magisk (27006)

### ISSUE THREAD

**Issue by The-Unforgiven-One** [entr0pia/trichromelibrary-squoosh#7]
Just an FYI that doing a clean install of the newest Magisk Canary's 27005 and 27006 has broken something in the install process for your module as it goes through the process like it is installing however after the reboot nothing shows in the Magisk log and the module folder and files are not present in the data/adb/modules folder. Thank you for your time.

**Comment by entr0pia** [comment]
try v1.5

**Comment by The-Unforgiven-One** [comment]
That fixed the issue. Thank You.
